#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 12 07:42:51 UTC 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim nexys_rf_riscv_behav -key {Behavioral:sim_1:Functional:nexys_rf_riscv} -tclbatch nexys_rf_riscv.tcl -log simulate.log"
xsim nexys_rf_riscv_behav -key {Behavioral:sim_1:Functional:nexys_rf_riscv} -tclbatch nexys_rf_riscv.tcl -log simulate.log

